function latex_new = latexTable_add_row_top(latex, row_to_add, options)
%LATEXTABLE_ADD_ROW_TOP Add a row at the top of the latex table generated
%by 'latexTable' (Dunisch, 2016), after '\toprule'
%   latex: the struct generated by 'latexTable'
%   row_to_add: content of the row to add in cell array format
    arguments
        latex
        row_to_add cell
        options.span double = repmat(1, numel(row_to_add), 1)
        options.cmidrule logical = false
    end
    for i = 1:numel(row_to_add)
        if options.span(i) > 1
            row_to_add{i} = ['\multicolumn{', num2str(options.span(i)), '}{c}{', row_to_add{i}, '}'];
        end
    end
    new_line = [' & ', strjoin(row_to_add, ' & '), ' \\'];
    if options.cmidrule
        index = 2;
        for i = 1:numel(row_to_add)
            index_min = index;
            index_max = index_min + options.span(i) - 1;
            new_line = [new_line, ' \cmidrule(lr){', num2str(index_min), '-', num2str(index_max), '}'];
            index = index_max + 1;
        end
    end
    index_before_top_rule = find(strcmp(latex, '\toprule'));
    if ismissing(index_before_top_rule)
        index_before_top_rule = find(startsWith(latex, '\begin{tabular}'));
    end
    latex_before_toprule = latex(1:index_before_top_rule);
    latex_after_toprule = latex((index_before_top_rule + 1):end);
    latex_new = [latex_before_toprule; new_line; latex_after_toprule];
end