function tableRowLabels_new = regTable_wrap_row(tableRowLabels, delimiter, delimiter_max, delimiter_join)
%LATEX_WRAP_RPW Wrap the text in the row labels to save horizontal space
%for row labels generated by 'stackResult2regTable'
%   tableRowLabels: generated row labels
%   delimiter: a string of delimiter to identify the location of line break
%   delimiter_max: the maximum number of delimiter in the line to break
%   delimiter_join: a string of delimiter to rejoin the strings
    for i = 1:numel(tableRowLabels)
        rowLabel = tableRowLabels{i};
        if rem(i, 2) == 1 && count(rowLabel, delimiter) >= delimiter_max
            rowLabel_split = split(rowLabel, delimiter);
            tableRowLabels{i} = strjoin(rowLabel_split(1:delimiter_max), delimiter_join);
            tableRowLabels{i + 1} = strcat(delimiter, strjoin(rowLabel_split((delimiter_max + 1):end), delimiter_join));
        end
    end
    tableRowLabels_new = tableRowLabels;
end