function VARirplot_new(IR, VARopt, INF, SUP, options)
%VARIRPLOT_NEW Plot the Impulse Response Function given a VAR model
%generated by the 'VAR toolbox 3.0' by Ambrogio Cesa-Bianchi
%   IR: IRF matrix
%   VARopt: options of the VAR model (VARopt)
%   INF: lower error bound
%   SUP: upper error bound
    arguments
        IR
        VARopt
        INF
        SUP
        options.LineStyle (1, 1) string = '-'
        options.LineWidth (1, 1) {mustBeNumeric} = get(groot, 'defaultLineLineWidth')
    end
    % preset
    vnames = VARopt.vnames;
    if isempty(VARopt.snames)
        snames = VARopt.vnames;
    else
        snames = VARopt.snames;
    end
    pick = VARopt.pick;
    [nsteps, nvars, nshocks] = size(IR);
    if pick<0 || pick>nvars
        error('The selected shock is non valid')
    else
        if pick == 0
            pick = 1;
        else
            nshocks = pick;
        end
    end
    %(nrow = nvars, ncol = nshocks)
    steps = 1:1:nsteps;
    x_axis = zeros(1, nsteps);
    % plot
    for i = 1:nvars
        for j = 1:nshocks
            subplot(nvars, nshocks, (j - 1) * nvars + i)
            plot(steps, IR(:, i, j), 'LineStyle', options.LineStyle, 'LineWidth', options.LineWidth)
            hold on
            plot(steps, INF(:, i, j), 'k:', 'LineWidth', 1)
            plot(steps, SUP(:, i, j), 'k:', 'LineWidth', 1)
            plot(x_axis, '--k', 'LineWidth', 0.5)
            hold on
            xlim([1 nsteps])
            title([vnames{i} ' to ' snames{j}])
            set(gca, 'Layer', 'top')
        end
    end
end